name: Report a broken page
description: Use this form to report any issues with a webpage, including instances where ads are not blocked or parts of the website fail to render or function properly.
body:
  - type: dropdown
    id: type
    attributes:
      label: What's happening?
      multiple: true
      options:
        - 🚫 Ads visible
        - 💬 Content unavailable
        - ✅ Consent issues
        - ⏯️ Website frozen
        - 🔒 Extension detected
        - Others

  - type: textarea
    attributes:
      label: Problematic URL(s)
      description: |
        Please provide the URL(s) where the issue occurs, as this information is essential for us to identify and resolve the problem.
      placeholder: |
        https://domain.tld/
      render: yaml
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Known browsers affected
      description: |
        It's helpful to prioritise testing on Chromium based browsers to debug complicated cases.
        If you do not select an option from the dropdown below, we will assume the issue occurs across all browsers.
      multiple: true
      options:
        - Chromium
        - Firefox
        - Firefox Android
        - Safari mobile
        - Safari macOS
        - Edge
        - Edge iOS
        - Edge Android
        - Opera
        - Brave
        - Other

  - type: textarea
    attributes:
      label: Description
      value: |
        <!-- IN CASE behaviour listing cannot describe the exact symptom -->
        <!-- OR you have additional details such as custom filters -->
        <!-- OR you have changed factory defaults (e.g. disablement of anti-tracking) -->
        <!-- PUT DESCRIPTION AFTER THIS LINE ⬇️ -->

        <!-- PUT DESCRIPTION BEFORE THIS LINE ⬆️ -->

        ### Reproduction steps

        1. Open the website

        ### Screenshots

        <details>
        <!-- PUT YOUR SCREENSHOTS AFTER THIS LINE ⬇️ -->

        <!-- PUT YOUR SCREENSHOTS BEFORE THIS LINE ⬆️ -->
        </details>

  - type: checkboxes
    attributes:
      label: Your privacy
      description: |
        By submitting this issue, you confirm that no personal information is included in any of the fields.
        If you're unsure whether your responses contain any personal information, we recommend [contacting our support channel to submit the issue](https://www.ghostery.com/support) instead.
        If personal information is found in the submission, we can assist with its removal, but please note that we cannot take responsibility for any data leaks.
      options:
        - label: I confirm that this issue does not contain any personal information and understand that Ghostery is not responsible for the issue content.
          required: true
