name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    path:
      - 'src/**'
      - 'test/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - run: bun run lint
