name: Publish @ghostery/config-types

on:
  push:
    branches:
      - main
    paths:
      - 'packages/config-types/src/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/config-types
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - run: deno install
      - run: deno run test
      - run: deno run build

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump version and publish
        run: |
          npm version patch --no-git-tag-version

          NEW_VERSION=$(node -p "require('./package.json').version")

          npm publish

          # Commit and push the version bump
          git add package.json
          git commit -m "chore: bump @ghostery/config-types to v${NEW_VERSION}"
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
