name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'filters/**'
  workflow_dispatch:

concurrency:
  group: "test"
  cancel-in-progress: false

jobs:
  test-config:
    runs-on: ubuntu-latest
    name: Test Config types
    defaults:
      run:
        working-directory: ./packages/config
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: deno run lint
        working-directory: ./
      - run: npm ci
      - run: npm run test
      - run: npm run build
