name: Test filters

on:
  push:
    branches:
      - main
    paths:
      - 'filters/**'
  pull_request:
    paths:
      - 'filters/**'
  workflow_dispatch:

concurrency:
  group: "test-filters"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: deno run lint
      - run: deno run tests
      - run: deno run build
