name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: "tests"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: deno run lint
      - run: deno run tests
      - run: deno run build
  test-config-types:
    runs-on: ubuntu-latest
    name: Test Config types
    defaults:
      run:
        working-directory: ./packages/config-types
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: npm ci
      - run: npm run test
      - run: npm run build
