name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: "tests"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - name: Read parameters
        id: read
        run: |
          echo "tool_versions="$(cat ./.tool_versions)"" >> "$GITHUB_OUTPUT"
      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          tool_versions: ${{ steps.read.outputs.tool_versions }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - run: bun run lint
      - run: bun run test
